id: IEDF40FCF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T11:33:39+00:00'
last_modified: '2022-06-10T04:52:54.643125+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3510
  title: གང་ཤར་རྡོ་རྗེའི་གླུ་ཕྲེང་སྐལ་བཟང་རྣ་བའི་དགའ་སྟོན། ཟབ་དོན་རྡོ་རྗེའི་གླུའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4646':
      image_group_id: I1KG3582
      title: Volume 1 of gang shar rdo rje'i glu phreng skal bzang rna ba'i dga' ston/
        zab don rdo rje'i glu'i skor
      total_pages: 568
      order: 1
      base_file: 4646.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
